-- Solicitações recebidas pelo formulário de contato do site da Inovai.
-- Base do futuro CRM de oportunidades: o e-mail avisa, esta tabela guarda.

create table if not exists public.contatos_site (
    id_contato   integer generated by default as identity primary key,
    nome         character varying not null,
    empresa      character varying not null,
    email        character varying,
    site         character varying,
    instagram    character varying,
    telefone     character varying,
    whatsapp     character varying not null,
    descricao    text not null,
    ip           character varying,
    -- Acompanhamento comercial, preenchido depois pela Inovai
    situacao     character varying not null default 'NOVO',
    observacoes  text,
    criado_em    timestamp without time zone not null default now(),
    atualizado_em timestamp without time zone not null default now()
);

create index if not exists ix_contatos_site_criado_em
    on public.contatos_site (criado_em desc);

-- Sem política: o acesso é só pelo Flask, com credencial de servidor.
-- A chave anônima do Supabase é pública e sem RLS qualquer um leria os
-- contatos comerciais pela API REST.
alter table public.contatos_site enable row level security;
